cat <<EOF > apps/youtil-be.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtil-be
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/1-team-YouTIL-k8s
    targetRevision: main
    path: helm/youtil-be
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: youtil-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF
